import streamlit as st
import pandas as pd
import gspread
from google.oauth2.service_account import Credentials
import json

# Configura Google Sheets
creds_json = st.secrets["GOOGLE_CREDENTIALS"]
creds_dict = json.loads(creds_json)
creds = Credentials.from_service_account_info(creds_dict)
client = gspread.authorize(creds)

# Apri il Google Sheet
SHEET_ID = "1keTMaYMtN0D-YIClxJFxYAKOMeb1ddKPIHH6Q92LxYw"  # Google Sheet ID
sheet = client.open_by_key(SHEET_ID).sheet1

# Titolo dell'app
st.title("Qualitative Performance Assessment of EndoDAC and Depth Pro Models")

st.write(
    "The video in the center shows a colonoscopy, while the two side videos (left and right) "
    "represent depth maps generated by two predictive models, where blue indicates deeper areas "
    "and red indicates shallower areas. \n"
    "Which of the two side videos (left or right) do you think best reflects reality in terms of accuracy in depth estimation?"
)

# Prima domanda: sei un medico?
clinician = st.radio("Are you a clinician?", ["Yes", "No"])

experience_level = None
procedures_performed = None
if clinician == "Yes":
    experience_level = st.radio("What is your experience level?", ["Specializzando", "Resident", "Esperto"])
    procedures_performed = st.radio(
        "How many endoscopic procedures have you performed?",
        ["<50", "Between 50 and 100", ">100"]
    )

# Nome
name = st.text_input("Please enter your name")

video_paths = [
    './VideoColonoscopy3.mp4',
    './VideoColonoscopy4.mp4',
    './VideoColonoscopy5.mp4',
    './VideoColonoscopy6.mp4',
    './VideoColonoscopy7.mp4',
    './VideoColonoscopy8.mp4',
    './VideoColonoscopy9.mp4',
    './VideoColonoscopy10.mp4',
    './VideoColonoscopy11.mp4',
    './VideoColonoscopy12.mp4',
]

# Stato della sessione
if "question_index" not in st.session_state:
    st.session_state["question_index"] = 0
if "responses" not in st.session_state:
    st.session_state["responses"] = [None] * len(video_paths)

# Se il nome è stato inserito, mostra il questionario
if name:
    st.header("Questionnaire")
    
    question_index = st.session_state["question_index"]
    
    st.subheader(f"Question {question_index + 1}")
    st.video(video_paths[question_index])
    
    existing_response = st.session_state["responses"][question_index]
    default_index = 0 if existing_response == "Left" else 1 if existing_response == "Right" else None
    
    response = st.radio(
        "Which of the two side videos (left or right) do you think best reflects reality in terms of accuracy in depth estimation?", 
        ["Left", "Right"], 
        key=f"question_{question_index}",
        index=default_index
    )
    
    st.session_state["responses"][question_index] = response
    
    col1, col2 = st.columns([1, 1])
    with col1:
        if st.button("Previous") and question_index > 0:
            st.session_state["question_index"] -= 1
            st.rerun()
    with col2:
        if st.button("Next") and question_index < len(video_paths) - 1:
            st.session_state["question_index"] += 1
            st.rerun()
    
    # Quando si inviano le risposte
    if question_index == len(video_paths) - 1 and st.button("Submit Answers"):
        new_data = [
            name,
            clinician,
            experience_level if clinician == "Yes" else None,
            procedures_performed if clinician == "Yes" else None,
        ] + [st.session_state["responses"][i] if st.session_state["responses"][i] else "No Response" for i in range(len(video_paths))]

        # Salva su Google Sheets
        sheet.append_row(new_data)
        st.success("Your answers have been saved!")

        st.stop()

# Visualizza le risposte salvate
st.subheader("Responses")
data = sheet.get_all_values()
if len(data) > 1:
    df = pd.DataFrame(data[1:], columns=data[0])
    st.dataframe(df)
else:
    st.write("No responses saved yet.")

